### ISSUE TITLE
Implement Login & Sign up Feature

### ISSUE THREAD

**Issue by jaypedia** [jaypedia/querouter#1]
- `/auth` 경로에 로그인, 회원가입 기능 개발 (로그인, 회원가입을 별도의 경로로 분리해도 무방)
  - [x] #4
- [x] #5
  - [x] 이메일 조건 : `@`, `.` 포함
  - [x] 비밀번호 조건 : 8자 이상 입력
  - [x] 이메일과 비밀번호가 모두 입력되어 있고 조건을 만족해야 제출 버튼이 활성화됨
- [x] #6
  - [x] `로그인 API`를 호출하고, 올바른 응답을 받았을 때 `루트 경로`로 이동시킴
  - [x] 응답으로 받은 `토큰`은 `로컬 스토리지`에 저장
  - [x] 다음 번에 로그인 시 `토큰`이 존재한다면 `루트 경로`로 리다이렉트
  - [x] 어떤 경우든 `토큰`이 유효하지 않다면 사용자에게 알리고 `로그인 페이지`로 리다이렉트
